name: Deploy to EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy Node.js App to AWS EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: SSH to EC2 and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          ENV_FILE: ${{ secrets.BE_ENV }}

        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            set -e

            cd /home/ubuntu/ggoomdole-service/apps/api

            git pull origin dev

            npx prisma generate

            pkill node || true

            nohup pnpm start > app.log 2>&1 &
          EOF